steps:
  - id: build-push
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -ex
        builddirs=(${_BUILD_DIRS})
        for img in ${builddirs[@]}; do
          docker build -t ${_REGISTRY}/${img}:latest ./${img}
          docker push ${_REGISTRY}/${img}:latest
        done

  - id: sign-latest
    name: 'gcr.io/projectsigstore/cosign'
    env:
      - 'TUF_ROOT=/tmp' # cosign tries to create $HOME/.sigstore
      - 'COSIGN_EXPERIMENTAL=1'
      - 'GOOGLE_SERVICE_ACCOUNT_NAME=cosign-signer@com-seankhliao.iam.gserviceaccount.com'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -ex
        builddirs=(${_BUILD_DIRS})
        for img in ${builddirs[@]}; do
          cosign sign ${_REGISTRY}/${img}:latest
        done
substitutions:
  _REGISTRY: us-central1-docker.pkg.dev/com-seankhliao/build
  _BUILD_DIRS: 'gotip firebase'
timeout: '900s' # gotip build is slow
