steps:
  - id: build-push
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -ex
        for img in gotip firebase; do
          docker build -t us-central1-docker.pkg.dev/com-seankhliao/build/${img}:latest ./${img}
          docker push us-central1-docker.pkg.dev/com-seankhliao/build/${img}:latest
        done

  - id: sign-latest
    name: 'gcr.io/projectsigstore/cosign'
    env:
      - 'TUF_ROOT=/tmp' # cosign tries to create $HOME/.sigstore
      - 'COSIGN_EXPERIMENTAL=1'
      - 'GOOGLE_SERVICE_ACCOUNT_NAME=cosign-signer@com-seankhliao.iam.gserviceaccount.com'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        for img in gotip firebase; do
          cosign sign us-central1-docker.pkg.dev/com-seankhliao/build/${img}:latest
        done
